spring:
  data:
    mongodb:
      database: security
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbit
    password: rabbit
  cloud:
    stream:
      bindings:
        usersCreatedEvent:
          group: securityService
          contentType: application/json
management:
  context-path: /uaa
server:
  port: 8989